Fixing network message names
CFC-Servers/cfc_restart pull request #6
Opened 2020-02-13 08:02 UTC by Claydo9

2020-02-13 08:46 UTC, brandonsturgeon commented
ok to test

2020-02-13 08:49 UTC, brandonsturgeon commented on lua/ulx/modules/sh/cfc_restart.lua
> +            local tw, th = surface.GetTextSize( txt ) -- Jenkins doesn't like th because it's unused but I have to leave it there because surface.GetTextSize() returns 2 things
```suggestion
            local tw, _ = surface.GetTextSize( txt )
```

I think technically if the second var is unused, you can do this:
```suggestion
            local tw = surface.GetTextSize( txt )
```

2020-02-14 08:42 UTC, Claydo9 commented
Ok, I've finally fixed this silly code! it's ready brandon.

2020-02-14 08:45 UTC, Claydo9 commented
Someone will probably have to re-write this though the code isn't very pleasant to read and some of the methods that the original creator used are just kind of bad i.e "Entity( 0 ):SetNWFloat( "CFC_SERVER_RESTART", math.max( 0, diff ) )"

2020-02-14 19:42 UTC, plally requested changes

2020-02-14 19:42 UTC, PLally commented on lua/ulx/modules/sh/cfc_restart.lua
> +            draw.WordBox( 0, ScrW() - tw, 10, txt, "TargetID", { r = 0, g = 0, b = 0, a = 180 }, { r = 255, g = 0, b = 0, a = 255} ) -- Says there is an "Unnecessary Parenthesies" but I see none
you  should probably use github comments for comments like this instead of putting it in the code

2020-02-14 19:42 UTC, PLally commented on lua/ulx/modules/sh/cfc_restart.lua
> +        local time = Entity( 0 ):GetNWFloat( "CFC_SERVER_RESTART", -1 )
i think it was originally changed to `thyme` to avoid shadowing the  global `time` variable
maybe changing it to something indicating what it actually represents  would be better than changing it back to `time`

2020-02-14 19:42 UTC, PLally commented on lua/ulx/modules/sh/cfc_restart.lua
> +CFC_SERVER_RESTART = { ["yes"] = false, ["time"] = 30 }
why did you change the table syntax to this?
personally i prefer defining tables like `{ yes = false, time = 30 }`

2020-02-14 19:42 UTC, PLally commented on lua/ulx/modules/sh/cfc_restart.lua
> +    CFC_SERVER_RESTART = { ["yes"] = true, ["time"] = SysTime() + tonumber( time ) }
same question about the table definition
it also might be worth it to just put it on multiple lines
e.g.
```lua
CFC_SERVER_RESTART = { 
    yes = true,
    time = etc,
}
```

2020-02-14 19:51 UTC, brandonsturgeon commented on lua/ulx/modules/sh/cfc_restart.lua
> +CFC_SERVER_RESTART = { ["yes"] = false, ["time"] = 30 }
we were diagnosing an issue with jenkins thinking there was a shadowed var

2020-02-14 19:53 UTC, brandonsturgeon commented on lua/ulx/modules/sh/cfc_restart.lua
> +        local time = Entity( 0 ):GetNWFloat( "CFC_SERVER_RESTART", -1 )
is there a global variable time? I know there's `os.time` but I can't find anything about `time` being something (though I thought so at first, too)

2020-02-14 19:55 UTC, PLally commented on lua/ulx/modules/sh/cfc_restart.lua
> +        local time = Entity( 0 ):GetNWFloat( "CFC_SERVER_RESTART", -1 )
ye, actually i dont think there is a  global time  variable
but that was the justification for doing it, well a `reserved keyword` was 
https://github.com/CFC-Servers/cfc_restart/commit/ab031e42fd127d34df057137a74fbb984cf68b19
:thinking:

2020-12-19 00:50 UTC, closed without merging